export const themes = {
  default: {
    background: 'from-gray-100 to-gray-200',
    card: 'bg-white',
    primary: 'from-blue-600 to-blue-700',
    secondary: 'from-purple-600 to-purple-700',
    accent: 'from-green-600 to-green-700',
    text: 'text-gray-800',
    highlightTrying: 'bg-green-100',
    highlightBacktrack: 'bg-red-100',
    highlightSuccess: 'bg-green-200',
    buttonText: 'text-white',
  },
  dark: {
    background: 'from-gray-800 to-gray-900',
    card: 'bg-gray-800',
    primary: 'from-blue-500 to-blue-600',
    secondary: 'from-purple-500 to-purple-600',
    accent: 'from-green-500 to-green-600',
    text: 'text-gray-100',
    highlightTrying: 'bg-blue-900',
    highlightBacktrack: 'bg-red-900',
    highlightSuccess: 'bg-green-900',
    buttonText: 'text-white',
  },
  solarized: {
    background: 'from-yellow-100 to-yellow-200',
    card: 'bg-yellow-50',
    primary: 'from-orange-500 to-orange-600',
    secondary: 'from-teal-500 to-teal-600',
    accent: 'from-cyan-500 to-cyan-600',
    text: 'text-gray-800',
    highlightTrying: 'bg-yellow-200',
    highlightBacktrack: 'bg-orange-300',
    highlightSuccess: 'bg-teal-200',
    buttonText: 'text-black',
  },
  nature: {
    background: 'from-green-100 to-green-200',
    card: 'bg-green-50',
    primary: 'from-green-700 to-green-800',
    secondary: 'from-brown-600 to-brown-700',
    accent: 'from-yellow-600 to-yellow-700',
    text: 'text-gray-900',
    highlightTrying: 'bg-green-300',
    highlightBacktrack: 'bg-brown-300',
    highlightSuccess: 'bg-yellow-300',
    buttonText: 'text-white',
  },
  neon: {
    background: 'from-black to-gray-800',
    card: 'bg-gray-900',
    primary: 'from-pink-600 to-pink-700',
    secondary: 'from-cyan-500 to-cyan-600',
    accent: 'from-lime-500 to-lime-600',
    text: 'text-pink-300',
    highlightTrying: 'bg-pink-700',
    highlightBacktrack: 'bg-cyan-700',
    highlightSuccess: 'bg-lime-700',
    buttonText: 'text-white',
  },
  pastel: {
    background: 'from-pink-100 to-pink-200',
    card: 'bg-white',
    primary: 'from-blue-300 to-blue-400',
    secondary: 'from-purple-300 to-purple-400',
    accent: 'from-green-300 to-green-400',
    text: 'text-gray-900',
    highlightTrying: 'bg-blue-200',
    highlightBacktrack: 'bg-purple-200',
    highlightSuccess: 'bg-green-200',
    buttonText: 'text-gray-800',
  },
  ocean: {
    background: 'from-blue-100 to-blue-200',
    card: 'bg-blue-50',
    primary: 'from-teal-600 to-teal-700',
    secondary: 'from-blue-500 to-blue-600',
    accent: 'from-indigo-500 to-indigo-600',
    text: 'text-gray-900',
    highlightTrying: 'bg-teal-200',
    highlightBacktrack: 'bg-indigo-200',
    highlightSuccess: 'bg-blue-200',
    buttonText: 'text-white',
  },
};
